### ISSUE TITLE
It it possible to keep the folder structure?

### ISSUE THREAD

**Issue by jdrupal-dev** [jonboh/obsidian2neorg#2]
Hi,

I have all my Obsidian notes organized in different folders.
Is it possible to keep that structure while the links between the documents are still working?

**Comment by jonboh** [comment]
Did the bulk transformation script fail to reproduce the folder structure in your notes?

**Comment by jdrupal-dev** [comment]
Yes it created a flat structure with all notes in the same directory.

**Comment by jdrupal-dev** [comment]
Ah, it works when using the lowercase links example.

**Comment by jonboh** [comment]
I think it should be fixed now for the other configuration as well (https://github.com/jonboh/obsidian2neorg/commit/51ac21da0854daed8974b7e64bb3c5d08e570e9a).
